### ISSUE TITLE
bump collectd version

### ISSUE THREAD

**Issue by m-richo** [cloudfoundry-community/collectd-boshrelease#11]
G'day,

Collectd 5.5 introduced some nice features for CPU aggregation.  I've tested it locally with local blob store and it works fine.  How can i assist with updating the boshrelease to include the newer version of collectd?  

can i simply be given `put` access to the `collectd-boshrelease` bucket and then raise a PR for upgrade to this repo?

Cheers,
Michael

**Comment by drnic** [comment]
Thanks @m-richo for pairing on this the other day.

I've pushed out a v2.1.0 release; and the release notes include the url/sha1 etc.
