### ISSUE TITLE
Open to new maintainers?

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry-community/collectd-boshrelease#12]
This repo hasn't been updated for a while, so we've been using a fork at https://github.com/18F/cg-collectd-boshrelease. Would you all be open to adding us as maintainers so we can review open issues and merge in our changes?

@simonjohansson

**Comment by wbean1** [comment]
+1 getting collectd 5.5.0+ into this is interesting to me, and it looks like previous requests/PRs have all stalled

**Comment by drnic** [comment]
@jmcarp @wbean1 anything in cloudfoundry-community organization is open to people taking over as new maintainers - everyone who is a "member" is probably an Owner and has full privileges to take over merging PRs, commiting to master etc. 

If you don't have S3 bucket access, email me and I'll create you credentials.

**Comment by drnic** [comment]
I've pushed out a v2.1.0 release; and the release notes include the url/sha1 etc.
