### ISSUE TITLE
Add collectd release to the official bosh releases list

### ISSUE THREAD

**Issue by claudio-benfatto** [cloudfoundry-community/collectd-boshrelease#20]
Hello here,

would it be possible to add the `collectd` bosh release to the official [bosh release list](https://bosh.io/releases).
It would make its usage more convenient.

In alternative, the project [github releases](https://github.com/cloudfoundry-community/collectd-boshrelease/releases) could contain a proper ready-to-use bosh release gzipped tar, instead of the standard github project archive

Thanks,
Claudio

**Comment by drnic** [comment]
@claudio-benfatto this release how has fancy CI https://ci.starkandwayne.com/teams/main/pipelines/collectd-boshrelease?groups=blobs&groups=collectd-boshrelease

It will automatically bump to new collectd versions; and the `shipit` task will automatically update `manifests/collectd.yml` with the latest final release URL/sha1. This release info is also appended to release notes https://github.com/cloudfoundry-community/collectd-boshrelease/releases/tag/v2.2.0

**Comment by claudio-benfatto** [comment]
That's great @drnic ! Many thanks!
